
name: Build and Deploy

on:

  push:

    branches:

      - master2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 11

        uses: actions/setup-java@v2

        with:

          java-version: 11
          distribution : 'adopt'

      # - name: Build with Maven

      #   run: mvn clean install

      # - name: Log Maven build output

      #   run: cat target/build.log

      # - name: Log Docker version

      #   run: docker version

      # - name: Build Docker image

      #   run: docker build -t myapp:latest .

      # - name: Log Docker image details

      #   run: docker images
